In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [12]:
df = pd.read_csv('data/raw.csv')

In [6]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group D,master's degree,standard,none,62,70,75
1,female,group C,bachelor's degree,free/reduced,completed,66,83,83
2,female,group D,some college,free/reduced,none,79,89,86
3,male,group C,master's degree,free/reduced,none,61,67,66
4,male,group E,high school,standard,none,73,64,57

In [7]:
df.shape

(801, 8)

In [8]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       801 non-null    str
 1   race_ethnicity               801 non-null    str
 2   parental_level_of_education  801 non-null    str
 3   lunch                        801 non-null    str
 4   test_preparation_course      801 non-null    str
 5   math_score                   801 non-null    int64
 6   reading_score                801 non-null    int64
 7   writing_score                801 non-null    int64
dtypes: int64(3), str(5)
memory usage: 50.2 KB

In [10]:
df.describe()

       math_score  reading_score  writing_score
count  801.000000     801.000000     801.000000
mean    66.475655      69.528090      68.436954
std     15.026218      14.472544      15.085799
min      8.000000      24.000000      15.000000
25%     57.000000      60.000000      58.000000
50%     66.000000      70.000000      69.000000
75%     77.000000      80.000000      79.000000
max    100.000000     100.000000     100.000000

In [13]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     77
reading_score                  69
writing_score                  71
dtype: int64

In [24]:
print(
    print('Gender',df.gender.unique()),
    print('race_ethnicity',df.race_ethnicity.unique()),
    print('parental_level_of_education',df.parental_level_of_education.unique()),
    print('Lunch',df.lunch.unique()),
    print('test_preparation_course',df.test_preparation_course.unique()),
#     print('math_score',df.math_score.unique()),
#     print('reading_score',df.reading_score.unique()),
#     print('writing_score',df.writing_score.unique())
)

Gender <StringArray>
['female', 'male']
Length: 2, dtype: str
race_ethnicity <StringArray>
['group D', 'group C', 'group E', 'group B', 'group A']
Length: 5, dtype: str
parental_level_of_education <StringArray>
[   'master's degree',  'bachelor's degree',       'some college',
        'high school', 'associate's degree',   'some high school']
Length: 6, dtype: str
Lunch <StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
test_preparation_course <StringArray>
['none', 'completed']
Length: 2, dtype: str
None None None None None

In [33]:
numerical_features = df.select_dtypes(include=['number']).columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

print(f"We have {len(numerical_features)} Numerical Features: {numerical_features}")
print(f"We have {len(categorical_features)} Categorical Features: {categorical_features}")

We have 3 Numerical Features: ['math_score', 'reading_score', 'writing_score']
We have 5 Categorical Features: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']