# Import required Libraries

In [35]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error,root_mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

# Import CSV Data

In [7]:
df = pd.read_csv('data/raw.csv')

# Top 5 Data

In [9]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group D,master's degree,standard,none,62,70,75
1,female,group C,bachelor's degree,free/reduced,completed,66,83,83
2,female,group D,some college,free/reduced,none,79,89,86
3,male,group C,master's degree,free/reduced,none,61,67,66
4,male,group E,high school,standard,none,73,64,57

# Preaparing X and Y variables

In [11]:
x = df.drop(columns = ["math_score"])

In [12]:
x.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,reading_score,writing_score
0,female,group D,master's degree,standard,none,70,75
1,female,group C,bachelor's degree,free/reduced,completed,83,83
2,female,group D,some college,free/reduced,none,89,86
3,male,group C,master's degree,free/reduced,none,67,66
4,male,group E,high school,standard,none,64,57

In [13]:
y = df.math_score

In [14]:
y.head()

0    62
1    66
2    79
3    61
4    73
Name: math_score, dtype: int64

In [37]:
num_features = x.select_dtypes(include=['number']).columns
cat_features = x.select_dtypes(include=['object', 'category']).columns

print (num_features,cat_features)

Index(['reading_score', 'writing_score'], dtype='str') Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='str')

C:\Users\APPLE COMPUTER\AppData\Local\Temp\ipykernel_8232\3773603675.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_features = x.select_dtypes(include=['object', 'category']).columns

In [16]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group D,master's degree,standard,none,62,70,75
1,female,group C,bachelor's degree,free/reduced,completed,66,83,83
2,female,group D,some college,free/reduced,none,79,89,86
3,male,group C,master's degree,free/reduced,none,61,67,66
4,male,group E,high school,standard,none,73,64,57

# Create Pipeline for Feature Engineering

In [25]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer


preprocesser = ColumnTransformer(
    [
        ('OneHotEncoder',OneHotEncoder(),cat_features),
        ('Scaling',StandardScaler(),num_features)
    ]
)

In [31]:
X = preprocesser.fit_transform(x)

In [33]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [34]:
x_train

array([[ 1.        ,  0.        ,  0.        , ...,  1.        ,
         0.169175  ,  0.16872944],
       [ 0.        ,  1.        ,  0.        , ...,  0.        ,
        -0.03840169, -0.22925646],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,
        -0.24597837,  0.03606747],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
        -1.21466956, -1.15789024],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
        -1.49143847, -1.09155926],
       [ 1.        ,  0.        ,  0.        , ...,  1.        ,
        -0.52274728, -0.36191843]], shape=(640, 19))

In [36]:
def evaluate_model():
    mae=mean_absolute_error()
    mse=mean_squared_error()
    rmse=root_mean_square_error()
    r2_score = r2_score()
    return mae,mse,rmse,r2_score

In [ ]:
models = {
"Linear Regression": Linear Regression (),
"Lasso": Lasso(),
"Ridge": Ridge(),
"K-Neighbors Regressor": KNeighborsRegressor(),
"Decision Tree": DecisionTreeRegressor(),
"Random Forest Regressor": RandomForestRegressor(),
"XGBRegressor": XGBRegressor(),
"CatBoosting Regressor": CatBoostRegressor(verbose=False),
"AdaBoost Regressor": AdaBoostRegressor()
}

model_list=[]
r2_list = []